/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tienda;

/**
 *
 * @author LUNA
 */
public class menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menu.class.getName());
    // Datos para el carrusel
    private String[] promos = {"¡Hoy venta de Hamburguesas!", "¡Quedan solo 3 Brazos de Reina, reserva por pedido!", "Prueba lo nuevo: Sushi Roll", "Remate de sabritas con ticket amarillo: 3x2"};
    private java.awt.Color[] colores = {new java.awt.Color(255, 230, 0), new java.awt.Color(255, 102, 102), new java.awt.Color(102, 204, 255), new java.awt.Color(204, 255, 153)};
    private int indiceActual = 0;
    private javax.swing.Timer timerCarrusel;
    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        personalizarDiseno();
        iniciarCarrusel();
    }
// lleva el teclado en la otra mochila
// ni leere esto no se ni por que lo pongo
// hola yo de en unas horas, no se te olvide quitar las lineas para que carguen las otras ventanas, eso suponiendo que pase por que no te pusiste a investigar si era como en python pero ahora ese es tu problema, es malo pensar asi pero ya no se que mas poner, estoy cansado
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCarousel = new javax.swing.JPanel();
        lblPromo = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnCategorias = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnOtros = new javax.swing.JButton();
        scrProductos = new javax.swing.JScrollPane();
        pnlGrid = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlCarousel.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout pnlCarouselLayout = new javax.swing.GroupLayout(pnlCarousel);
        pnlCarousel.setLayout(pnlCarouselLayout);
        pnlCarouselLayout.setHorizontalGroup(
            pnlCarouselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPromo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCarouselLayout.setVerticalGroup(
            pnlCarouselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPromo, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
        );

        btnInicio.setText("Perfil");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnCategorias.setText("Categorias");
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });

        btnCompras.setText("Compras");
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });

        btnOtros.setText("Config.");
        btnOtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCompras, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(btnOtros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCategorias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlGridLayout = new javax.swing.GroupLayout(pnlGrid);
        pnlGrid.setLayout(pnlGridLayout);
        pnlGridLayout.setHorizontalGroup(
            pnlGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );
        pnlGridLayout.setVerticalGroup(
            pnlGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        scrProductos.setViewportView(pnlGrid);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCarousel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrProductos)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCarousel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
    // Acción inmediata: Mostrar mensaje
    //javax.swing.JOptionPane.showMessageDialog(this, "Accediendo a tu historial de compras");
    tienda.compras m= new tienda.compras();
    m.setVisible(true);
    this.dispose();
    //tienda.Carrito m= new tienda.Carrito();
    //m.setVisible(true);
    //this.dispose();


    /* PARA NAVEGACIÓN FUTURA:
       new VentanaCompras().setVisible(true);
       this.setVisible(false); // Oculta esta ventana sin cerrarla del todo
    */
    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnOtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtrosActionPerformed
    // Acción inmediata: Mostrar mensaje
    //YA NO ES NECESARIO-->javax.swing.JOptionPane.showMessageDialog(this, "Abriendo menú de configuración y perfil");
    tienda.configuracion2 t1= new tienda.configuracion2();
    t1.setVisible(true);
    this.dispose();
    

    //PARA NAVEGACIÓN FUTURA:
       // Podrías abrir un JDialog (ventana emergente pequeña) para opciones
       //configuracion2 dial = new configuracion2(this, true);
       //dial.setVisible(true);
    
    }//GEN-LAST:event_btnOtrosActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        //javax.swing.JOptionPane.showMessageDialog(this, "Ya te encuentras en el Inicio");
        tienda.perfil t1= new tienda.perfil();
        t1.setVisible(true);
        this.dispose();

        /* PARA NAVEGACIÓN FUTURA:
        Si quieres recargar el panel principal o volver desde otra pantalla:
        this.setContentPane(new PanelInicio()); 
        this.revalidate();
        */// TODO add your handling code here:
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
// Acción inmediata: Mostrar mensaje
    //javax.swing.JOptionPane.showMessageDialog(this, "Abriendo Categorías...");
    tienda.categorias t1= new tienda.categorias();
    t1.setVisible(true);
    this.dispose();

    /*PARA NAVEGACIÓN FUTURA (Abrir otra ventana):
       VentanaCategorias vc = new VentanaCategorias();
       vc.setVisible(true);
       this.dispose(); // Cierra la ventana actual (Menú)
    */
    
    /*
       PARA NAVEGACIÓN TIPO WEB (Cambiar solo el contenido central):
       pnlGrid.removeAll(); // Limpia los productos actuales
       // Aquí llamarías a un método que cargue categorías en lugar de productossadmdaooomomaosmd
       pnlGrid.revalidate();
       pnlGrid.repaint();
    */
    }//GEN-LAST:event_btnCategoriasActionPerformed
// 1. Llama a este método en el constructor, justo después de initComponents();
private void personalizarDiseno() {
    // Configuración del Grid de productos (2 columnas, espacio de 10px)
    pnlGrid.setLayout(new java.awt.GridLayout(0, 2, 10, 10));
    pnlGrid.setBackground(new java.awt.Color(240, 240, 240));

    // Agregamos algunos productos de prueba
    agregarProducto("Hamburguesa Doble", "$ 8.50");
    agregarProducto("Pizza Familiar", "$ 12.00");
    agregarProducto("Sushi Roll (10pcs)", "$ 9.90");
    agregarProducto("Tacos al Pastor", "$ 5.00");
    agregarProducto("Ensalada Caesar", "$ 6.50");
    agregarProducto("Ramen Especial", "$ 11.00");

    // Refrescar el panel para que NetBeans muestre los cambios
    pnlGrid.revalidate();
    pnlGrid.repaint();
}

// 2. Método para generar las "tarjetas" de comida dinámicamente
private void agregarProducto(String nombre, String precio) {
    // Creamos un panel pequeño para cada producto
    javax.swing.JPanel card = new javax.swing.JPanel();
    card.setLayout(new java.awt.BorderLayout());
    card.setBackground(java.awt.Color.WHITE);
    card.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));

    // Espacio para la imagen (Icono)
    javax.swing.JLabel lblImagen = new javax.swing.JLabel("[Imagen]");
    lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblImagen.setPreferredSize(new java.awt.Dimension(100, 100));
    
    // Panel de texto (Nombre y Precio)
    javax.swing.JPanel pnlInfo = new javax.swing.JPanel();
    pnlInfo.setLayout(new java.awt.GridLayout(2, 1));
    pnlInfo.setBackground(java.awt.Color.WHITE);
    pnlInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

    javax.swing.JLabel lblNombre = new javax.swing.JLabel(nombre);
    lblNombre.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
    
    javax.swing.JLabel lblPrecio = new javax.swing.JLabel(precio);
    lblPrecio.setForeground(new java.awt.Color(0, 153, 51)); // Verde Mercado Libre

    pnlInfo.add(lblNombre);
    pnlInfo.add(lblPrecio);

    card.add(lblImagen, java.awt.BorderLayout.CENTER);
    card.add(pnlInfo, java.awt.BorderLayout.SOUTH);

    pnlGrid.add(card);
}
// tanto solo para productos, tnego sueñooooooooooooooooaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
private void iniciarCarrusel() {
    // Configuramos un timer que se ejecute cada 3000ms (3 segundos)
    timerCarrusel = new javax.swing.Timer(3000, (java.awt.event.ActionEvent e) -> {
        // Aumentar el índice y volver a 0 si llegamos al final
        indiceActual = (indiceActual + 1) % promos.length;
        
        // Actualizar el diseño del panel que creaste en NetBeans
        pnlCarousel.setBackground(colores[indiceActual]);
        lblPromo.setText(promos[indiceActual]);
        
        // Efecto de refresco
        pnlCarousel.revalidate();
        pnlCarousel.repaint();
    });
    
    timerCarrusel.start(); // ¡Arranca el movimiento!
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategorias;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnOtros;
    private javax.swing.JLabel lblPromo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlCarousel;
    private javax.swing.JPanel pnlGrid;
    private javax.swing.JScrollPane scrProductos;
    // End of variables declaration//GEN-END:variables
}
