/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ADMIN;
import conexion.conexionMysql;
import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 *
 * @author zurim
 */
public class AgregarCategoria extends javax.swing.JDialog {
    private PanelCategorias panel;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgregarCategoria.class.getName());

    /**
     * Creates new form AgregarCategoria
     */
    public AgregarCategoria(java.awt.Frame parent, boolean modal, PanelCategorias panel) {
    super(parent, modal);
    initComponents();
    this.panel = panel;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NombreCategoria = new javax.swing.JTextField();
        DescripcionCategoria = new javax.swing.JTextField();
        CancelarCat = new javax.swing.JButton();
        GuardarCat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nombre de la categoria");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Descripcion:");

        NombreCategoria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NombreCategoria.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        DescripcionCategoria.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DescripcionCategoria.addActionListener(this::DescripcionCategoriaActionPerformed);

        CancelarCat.setText("Cancelar");
        CancelarCat.addActionListener(this::CancelarCatActionPerformed);

        GuardarCat.setText("Guardar Categoria");
        GuardarCat.addActionListener(this::GuardarCatActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DescripcionCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(NombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(219, 219, 219)
                            .addComponent(GuardarCat)
                            .addGap(18, 18, 18)
                            .addComponent(CancelarCat)))
                    .addContainerGap(41, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DescripcionCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GuardarCat)
                        .addComponent(CancelarCat))
                    .addGap(42, 42, 42)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DescripcionCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripcionCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionCategoriaActionPerformed

    private void GuardarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCatActionPerformed
        // TODO add your handling code here:
        guardarCategoria();
    }//GEN-LAST:event_GuardarCatActionPerformed

    private void CancelarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarCatActionPerformed
        // TODO add your handling code here:
        CancelarCat.addActionListener(e -> dispose());
    }//GEN-LAST:event_CancelarCatActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarCat;
    private javax.swing.JTextField DescripcionCategoria;
    private javax.swing.JButton GuardarCat;
    private javax.swing.JTextField NombreCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
public void guardarCategoria() {
    if (NombreCategoria.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Escribe un nombre");
        return;
    }

    Connection con = conexionMysql.conectar();

    String sql = "INSERT INTO categoria(nombre_categoria, descripcion) VALUES (?, ?)";

    try {
        PreparedStatement ps = con.prepareStatement(sql);

        ps.setString(1, NombreCategoria.getText());
        ps.setString(2, DescripcionCategoria.getText());

        ps.executeUpdate();

        javax.swing.JOptionPane.showMessageDialog(this, "Categoria guardada");

        panel.cargarCategorias(); 

        dispose();

    } catch (Exception e) {
        System.out.println("Error: " + e);
    }
}
}
