/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ADMIN;

/**
 *
 * @author LUNA
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form Productos
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCentral = new javax.swing.JPanel();
        PanelOpciones = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        BotonProductos = new javax.swing.JButton();
        BotonOrdenes = new javax.swing.JButton();
        BotonCategorias = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        BotonSalir = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelCentral.setLayout(new java.awt.BorderLayout());

        PanelOpciones.setBackground(new java.awt.Color(255, 0, 0));
        PanelOpciones.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        PanelOpciones.setPreferredSize(new java.awt.Dimension(150, 551));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Opciones"));
        jPanel5.setPreferredSize(new java.awt.Dimension(138, 300));
        jPanel5.setLayout(new java.awt.GridLayout(5, 5));

        BotonProductos.setText("Productos");
        BotonProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonProductosActionPerformed(evt);
            }
        });
        jPanel5.add(BotonProductos);

        BotonOrdenes.setText("Ordenes");
        BotonOrdenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOrdenesActionPerformed(evt);
            }
        });
        jPanel5.add(BotonOrdenes);

        BotonCategorias.setText("Categorias");
        BotonCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCategoriasActionPerformed(evt);
            }
        });
        jPanel5.add(BotonCategorias);

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelOpcionesLayout = new javax.swing.GroupLayout(PanelOpciones);
        PanelOpciones.setLayout(PanelOpcionesLayout);
        PanelOpcionesLayout.setHorizontalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PanelOpcionesLayout.setVerticalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelCentral.add(PanelOpciones, java.awt.BorderLayout.LINE_START);

        contentPanel.setBackground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        PanelCentral.add(contentPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonProductosActionPerformed
        // 1. Instanciamos la vista
        PanelProductos vista = new PanelProductos();
        // 2. Configuramos el tamaño para que llene el espacio disponible
        vista.setSize(contentPanel.getWidth(), contentPanel.getHeight());
        vista.setLocation(0, 0);
        // 3. Limpiamos lo que haya en el centro y ponemos la nueva vista
        contentPanel.removeAll();
        contentPanel.add(vista, java.awt.BorderLayout.CENTER);
    
        // 4. ¡Súper importante! Refrescamos la interfaz
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_BotonProductosActionPerformed

    private void BotonCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCategoriasActionPerformed
        // TODO add your handling code here:
        PanelCategorias vista = new PanelCategorias();
        // 2. Configuramos el tamaño para que llene el espacio disponible
        vista.setSize(contentPanel.getWidth(), contentPanel.getHeight());
        vista.setLocation(0, 0);
        // 3. Limpiamos lo que haya en el centro y ponemos la nueva vista
        contentPanel.removeAll();
        contentPanel.add(vista, java.awt.BorderLayout.CENTER);
    
        // 4. ¡Súper importante! Refrescamos la interfaz
        contentPanel.revalidate();
        contentPanel.repaint();
        
    }//GEN-LAST:event_BotonCategoriasActionPerformed

    private void BotonOrdenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOrdenesActionPerformed
        // TODO add your handling code here:
        PanelOrdenes vista = new PanelOrdenes();
        // 2. Configuramos el tamaño para que llene el espacio disponible
        vista.setSize(contentPanel.getWidth(), contentPanel.getHeight());
        vista.setLocation(0, 0);
        // 3. Limpiamos lo que haya en el centro y ponemos la nueva vista
        contentPanel.removeAll();
        contentPanel.add(vista, java.awt.BorderLayout.CENTER);
    
        // 4. ¡Súper importante! Refrescamos la interfaz
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_BotonOrdenesActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
        tienda.Login regresar= new tienda.Login();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCategorias;
    private javax.swing.JButton BotonOrdenes;
    private javax.swing.JButton BotonProductos;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JPanel PanelCentral;
    private javax.swing.JPanel PanelOpciones;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
